### ISSUE TITLE
Incorrectly identifies URLs when they are a substring of a Company URL

### ISSUE THREAD

**Issue by jseppi** [tmcw/cream#3]
For example, when visiting http://company.wizards.com CREAM identifies the site as belonging to money-wizards, whose entry in the companies object is `money-wizards.com`

This is because the strings are reversed, which causes `test("moc.sdraziw-yenom", "moc.sdraziw")` to return `true`.

**Comment by jseppi** [comment]
(don't judge my example url :grimacing:)

**Comment by tmcw** [comment]
Yep... definitely need a more robust url matcher. Will mull on this, also open to suggestions.
